# Generated by Django 4.2.1 on 2023-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('MobileNumber', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('BloodGroup', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Volumedonated', models.CharField(max_length=255)),
                ('Dateofdonation', models.CharField(max_length=255)),
            ],
        ),
    ]
